<a href="https://colab.research.google.com/github/usneek/Multilingual-Conversational-Question-Answering/blob/main/ChatBot_MuRIL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q -U tensorflow-text
!pip install -q tf-models-official

     |████████████████████████████████| 4.4 MB 31.3 MB/s 
     |████████████████████████████████| 1.8 MB 27.1 MB/s 
     |████████████████████████████████| 90 kB 10.1 MB/s 
     |████████████████████████████████| 636 kB 50.5 MB/s 
     |████████████████████████████████| 213 kB 77.1 MB/s 
     |████████████████████████████████| 1.1 MB 41.3 MB/s 
     |████████████████████████████████| 1.2 MB 59.7 MB/s 
     |████████████████████████████████| 37.1 MB 52 kB/s 
     |████████████████████████████████| 43 kB 2.1 MB/s 
     |████████████████████████████████| 99 kB 9.6 MB/s 
     |████████████████████████████████| 352 kB 48.1 MB/s 


In [ ]:
import pandas as pd
import numpy as np
np.random.seed(0)
from keras.regularizers import l2
from keras.models import Model, Sequential
from keras.layers import Dense, Input, Dropout, LSTM, Activation, Conv1D, Flatten
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
from keras.initializers import glorot_uniform
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
import tensorflow as tf
from sklearn.metrics import f1_score
np.random.seed(1)
import tensorflow_hub as hub
import tensorflow_text as text
from official.nlp import optimization
import matplotlib.pyplot as plt
import re
import string
import seaborn as sns
tf.get_logger().setLevel('ERROR')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import json
data_file = open('drive/My Drive/Conversational Question Answering System Code Notebooks/data.json',encoding='utf-8').read()
intents = json.loads(data_file)

In [ ]:
sentence=[]
for intent in intents['intents']:
    for pattern in intent['patterns']:
        sentence.append(pattern)

In [ ]:
classes=[]
for intent in intents['intents']:
  for pattern in intent['patterns']:
    classes.append(intent['tag'])

In [ ]:
print(sentence)

['सीज़ेंट्रिक्स कॉलबैक', 'सीजेड कैक्लबैक', 'सीज़ेंट्रिक्स कॉल बैक', 'C केंद्र कॉल बैक', 'सीज़ेंट्रिक्स कॉल बैक', 'वापस कॉल करें', 'क्या आप कॉल बैक सुविधा प्रदान करते हैं', 'कॉल बैक सॉल्यूशन', 'एक कॉल बैक समाधान की तलाश में', 'कॉल बैक सेवा की आवश्यकता है', 'कॉल बैक सॉल्यूशन है', 'सीज़ेंट्रिक्स कॉलबैक क्या है', 'क्या आप मुझे सीज़ेंट्रिक्स कॉलबैक समाधान में मदद कर सकते हैं', 'क्या आप मुझे सीज़ेंट्रिक्स कॉल बैक सॉल्यूशन में मदद कर सकते हैं', 'क्या आप मुझे कॉल बैक समाधान के बारे में बता सकते हैं', 'ठीक है धन्यवाद मुझे सीज़ेंट्रिक्स कॉलबैक के बारे में बताओ', 'धन्यवाद, मुझे कॉलबैक के बारे में बताएं', 'थैंक्यू, कॉल बैक क्या है', 'अच्छा, क्या आप मुझे कॉलबैक के बारे में बता सकते हैं?', 'धन्यवाद मुझे सीज़ेंट्रिक्स कॉलबैक के बारे में बताएं', ' सीज़ेंट्रिक्स हेल्पडेस्क', 'सीज़ेंट्रिक्सहेल्पडेस्क', 'सीज़ेंट्रिक्स मदद', 'सीज़ेंट्रिक्स हेल्पडेस्क', 'मदद', 'सहायता केंद्र', 'हेल्प डेस्क', 'सीज़ेंट्रिक्स हेल्पडेस्क', 'क्या आप हेल्पडेस्क सुविधा प्रदान करते हैं', 'एक हेल्प डेस्क समाधान की तलाश में', 'मदद ड

In [ ]:
print(classes)

['cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_callback', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'cz_helpdesk', 'crm_application', 'crm_application', 'crm_application', 'crm_application', 'crm_application', 'crm_application', 'crm_application', 'crm_application', 'crm_application', 'crm_application', 'crm_application', 'crm_application', 'crm_application', 'crm_application', 'crm_application', 'non_voice_process', 'non_voice_process', 'non_voice_process', 'non_voice_process', 'non_voice_process', 'non_voice_process', 'no

In [ ]:
from numpy import array
from numpy import argmax
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
encoder = LabelEncoder()
encoder.fit(classes)
encoded_Y = encoder.transform(classes)
encoded_Y=np_utils.to_categorical(encoded_Y)

In [ ]:
print(encoded_Y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
X=[]
for i in sentence:
  X.append(i)

In [ ]:
print(X)

['सीज़ेंट्रिक्स कॉलबैक', 'सीजेड कैक्लबैक', 'सीज़ेंट्रिक्स कॉल बैक', 'C केंद्र कॉल बैक', 'सीज़ेंट्रिक्स कॉल बैक', 'वापस कॉल करें', 'क्या आप कॉल बैक सुविधा प्रदान करते हैं', 'कॉल बैक सॉल्यूशन', 'एक कॉल बैक समाधान की तलाश में', 'कॉल बैक सेवा की आवश्यकता है', 'कॉल बैक सॉल्यूशन है', 'सीज़ेंट्रिक्स कॉलबैक क्या है', 'क्या आप मुझे सीज़ेंट्रिक्स कॉलबैक समाधान में मदद कर सकते हैं', 'क्या आप मुझे सीज़ेंट्रिक्स कॉल बैक सॉल्यूशन में मदद कर सकते हैं', 'क्या आप मुझे कॉल बैक समाधान के बारे में बता सकते हैं', 'ठीक है धन्यवाद मुझे सीज़ेंट्रिक्स कॉलबैक के बारे में बताओ', 'धन्यवाद, मुझे कॉलबैक के बारे में बताएं', 'थैंक्यू, कॉल बैक क्या है', 'अच्छा, क्या आप मुझे कॉलबैक के बारे में बता सकते हैं?', 'धन्यवाद मुझे सीज़ेंट्रिक्स कॉलबैक के बारे में बताएं', ' सीज़ेंट्रिक्स हेल्पडेस्क', 'सीज़ेंट्रिक्सहेल्पडेस्क', 'सीज़ेंट्रिक्स मदद', 'सीज़ेंट्रिक्स हेल्पडेस्क', 'मदद', 'सहायता केंद्र', 'हेल्प डेस्क', 'सीज़ेंट्रिक्स हेल्पडेस्क', 'क्या आप हेल्पडेस्क सुविधा प्रदान करते हैं', 'एक हेल्प डेस्क समाधान की तलाश में', 'मदद ड

In [ ]:
!pip install sentence-transformers

     |████████████████████████████████| 78 kB 6.9 MB/s 
     |████████████████████████████████| 2.9 MB 40.5 MB/s 
     |████████████████████████████████| 3.3 MB 53.1 MB/s 
     |████████████████████████████████| 56 kB 5.5 MB/s 
     |████████████████████████████████| 895 kB 42.1 MB/s 
     |████████████████████████████████| 109 kB 74.7 MB/s 
     |████████████████████████████████| 546 kB 60.6 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.1.0-py3-none-any.whl size=121000 sha256=b7831cb55ccebb2d14726eb7f464fb0a772732dda9dd69237993081b56f68266
  Stored in directory: /root/.cache/pip/wheels/90/f0/bb/ed1add84da70092ea526466eadc2bfb197c4bcb8d4fa5f7bad
Successfully built sentence-transformers


In [ ]:
from sentence_transformers import SentenceTransformer
sbert_model = SentenceTransformer('google/muril-base-cased')

Downloading:   0%|          | 0.00/736 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/9.04k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/411 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/953M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/113 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/181 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.16M [00:00<?, ?B/s]

Some weights of the model checkpoint at /root/.cache/torch/sentence_transformers/google_muril-base-cased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.bias', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
sentence_embedding=sbert_model.encode(X)

/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2227: UserWarning: `max_length` is ignored when `padding`=`True`.
  warnings.warn("`max_length` is ignored when `padding`=`True`.")


In [ ]:
model = Sequential()
model.add(Dense(256, input_shape=(sentence_embedding.shape[1],), activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(33, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) 
hist = model.fit(sentence_embedding,encoded_Y, epochs=600, batch_size=10, verbose=1)
model.save('chatbot_model.h5', hist)
print("model created")

In [ ]:
import random
def getResponse(ints, intents_json):
    tag = ints[0]['intent']
    list_of_intents = intents_json['intents']
    for i in list_of_intents:
        if(i['tag']== tag):
            result = random.choice(i['responses'])
            break
    return result

In [ ]:
final=['','affirm','crm_application','cz_acd','cz_bar','cz_bot','cz_callback',
 'cz_callblast','cz_chat','cz_conference','cz_dialer','cz_guide',
 'cz_helpdesk','cz_ivr','cz_lms','cz_magic_call','cz_missed_call',
 'cz_mobile','cz_screen_logger','cz_voice_logger','deny','greet','home',
 'manual_dialer','non_voice_process','predictive_dialer','preview_dialer',
 'product','progressive_dialer','self_service_solutions','thankyou',
 'voice_process','work_force_management']

In [ ]:
def chatbot_response(text):
  text=[text]
  em=sbert_model.encode(text)
  res = model.predict(em)[0]
  ERROR_THRESHOLD = 0.3
  results = [[i,r] for i,r in enumerate(res) if r>ERROR_THRESHOLD]
  results.sort(key=lambda x: x[1], reverse=True)
  return_list = []
  for r in results:
      return_list.append({"intent": final[r[0]], "probability": str(r[1])})
  res = getResponse(return_list, intents)
  print(res)
 

In [ ]:
chatbot_response("सीज़ेंट्रिक्स कॉलबैक")

सीज़ेंट्रिक्स कॉलबैक समाधान आपके भावी ग्राहकों को लंबे समय तक कॉल पर प्रतीक्षा नहींकरने में मदद करता है। उन्हें तुरंत कॉल करें या उनकी सुविधानुसार कॉल शेड्यूल  करें। आगंतुक या ग्राहक अपना संपर्क नंबर प्रदान कर सकते हैं और संबंधित एजेंटवापस कॉल करेंगे। यह आपके ग्राहक के ड्रॉपआउट दरों को बचाता है। अधिक जानकारी केलिए लिंक पर जाएं


/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2227: UserWarning: `max_length` is ignored when `padding`=`True`.
  warnings.warn("`max_length` is ignored when `padding`=`True`.")


In [ ]:
chatbot_response("kya aapke paas dialer ka progressive mode hai")

सीज़ेंट्रिक्स मोबाइल, मोबाइल पहला समाधान है जो लैपटॉप / डेस्कटॉप / PRI / लैंडलाइन पर एजेंटों की निर्भरता को हटाकर और उनके स्मार्टफ़ोन पर टेलीफोनी लाकर अधिक गतिशीलता को प्रोत्साहित करता है। यह बिक्री, सहायता और संग्रह में वितरित कार्यबल के लिए काफी हद तक उपयोगी है। अधिक जानकारी के लिए लिंक पर जाएं,<a href='https://www.czentrix.com/products/czmobile'>यहाँ क्लिक करें</a>


/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2227: UserWarning: `max_length` is ignored when `padding`=`True`.
  warnings.warn("`max_length` is ignored when `padding`=`True`.")


In [ ]:
chatbot_response("हांजी")

आपकी प्रतिक्रिया के लिए आपका धन्यवाद। होम पर जाए


/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2227: UserWarning: `max_length` is ignored when `padding`=`True`.
  warnings.warn("`max_length` is ignored when `padding`=`True`.")


In [ ]:
chatbot_response("hello")

सीज़ेंट्रिक्स चैट टेक्स्ट, ऑडियो और वीडियो चैट प्रदान करता है। सोशल मीडिया चैट और व्हाट्सएप के साथ इसका एकीकरण केक पर आइसिंग जोड़ता है। चैट विंडो को दिखाने के लिए लचीलापन है, उस पर क्या दिखाना है और अपने ग्राहक की यात्रा के अनुसार संदेशों को अनुकूलित करना है। अधिक जानकारी के लिए लिंक पर जाएं,<a href='https://www.czentrix.com/products/czchat'>यहाँ क्लिक करें</a>


/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2227: UserWarning: `max_length` is ignored when `padding`=`True`.
  warnings.warn("`max_length` is ignored when `padding`=`True`.")


In [ ]:
chatbot_response("मिस्ड कॉल के बारे में बताओ")

सीज़ेड मिस्ड कॉल समाधान उत्पन्न लीड की तरह बहुत कुछ कर सकता है, अंत उपयोगकर्ताओं को कनेक्ट करने, संख्याओं की पुष्टि करने, प्रतिक्रिया एकत्र करने, वोटों का संचालन करने और यहां तक कि प्रतियोगिता चलाने के लिए एक निःशुल्क मंच प्रदान करता है। उपयोगकर्ता बस एक मिस्ड कॉल कर सकता है और हमारे समाधान द्वारा आराम का ध्यान रखा जाता है। अधिक जानकारी के लिए यात्रा लिंक,<a href='https://www.czentrix.com/products/czmissedcallservice'>यहाँ क्लिक करें</a>


/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2227: UserWarning: `max_length` is ignored when `padding`=`True`.
  warnings.warn("`max_length` is ignored when `padding`=`True`.")


In [ ]:
chatbot_response("Tell me about dialers")

सीज़ेंट्रिक्स डायलर न केवल आपको डेटाबेस आयात करने का एक आसान विकल्प देता है, बल्कि वेबसाइट, सीआरएम, एलएमएस आदि जैसे तीसरे पक्ष के लीड स्रोतों के साथ आसानी से एकीकृत करता है ताकि लीड सीधे डायलर से वास्तविक समय में जुड़ सकें। चार प्रकार के डायलर हैं 1. प्रडिक्टिव डायलर 2. प्रॊगरेशिव डायलर 3. प्रीव्यू डायलर 4. मैनुअल डायलर


/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2227: UserWarning: `max_length` is ignored when `padding`=`True`.
  warnings.warn("`max_length` is ignored when `padding`=`True`.")


In [ ]:
chatbot_response("ਮੈਨੂੰ ਡਾਇਲਰ ਬਾਰੇ ਦੱਸੋ")

सीज़ेंट्रिक्स डायलर न केवल आपको डेटाबेस आयात करने का एक आसान विकल्प देता है, बल्कि वेबसाइट, सीआरएम, एलएमएस आदि जैसे तीसरे पक्ष के लीड स्रोतों के साथ आसानी से एकीकृत करता है ताकि लीड सीधे डायलर से वास्तविक समय में जुड़ सकें। चार प्रकार के डायलर हैं 1. प्रडिक्टिव डायलर 2. प्रॊगरेशिव डायलर 3. प्रीव्यू डायलर 4. मैनुअल डायलर


/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2227: UserWarning: `max_length` is ignored when `padding`=`True`.
  warnings.warn("`max_length` is ignored when `padding`=`True`.")
